DROP DATABASE IF EXISTS dat257;
DROP ROLE IF EXISTS dat257;

CREATE USER dat257 WITH PASSWORD 'dat257';
CREATE DATABASE dat257;
ALTER DATABASE dat257 OWNER TO dat257;
\c dat257

CREATE TABLE Sightings (
  id SERIAL PRIMARY KEY,
  userid INTEGER NOT NULL,
  lat INTEGER NOT NULL,
  long INTEGER NOT NULL,
  time INTEGER NOT NULL DEFAULT (extract(epoch from now()))
);
ALTER TABLE Sightings OWNER TO dat257;
